### ISSUE TITLE
Any way to specify a README.md instead of .Rmd?

### ISSUE THREAD

**Issue by palermog** [maRce10/sketchy#13]
Hello! I'm using your package to generate a compendium and hoping to use `holepunch` to prepare it for binderizing. Otherwise, do you have any recommendations on how to best automate rendering a .md file for GH from the .Rmd? Thanks!

**Comment by maRce10** [comment]
Hi, 

that's really cool. You could use `rmarkdown::render()` right after creating the compendium to do that. For instance:

```
make_compendium(name = "projX", format = "basic", force = TRUE, path = tempdir())

rmarkdown::render(file.path(tempdir(), "projX", "README.Rmd"))

```

That will create the md from the Rmd

I will try to incorporate that so the md file is also there when the project is created

**Comment by maRce10** [comment]
OK I added that feature so now it should create the md file as well

**Comment by palermog** [comment]
Thank you, that's wonderful!
