### ISSUE TITLE
Error when using rdir as format when creating a compendium

### ISSUE THREAD

**Issue by andreaarriaga** [maRce10/sketchy#14]
In console the code is

> sketchy::make_compendium(path = ruta, name = "rdir", format = "rdir")
Creating directories ...
Error: cannot create directory '/home/andrea/Downloads/borrar/rdir/data/raw'
In addition: Warning message:
In dir.create(path) :
  cannot create dir '/home/andrea/Downloads/borrar/rdir/data/raw', reason 'No such file or directory'

The structure of the file created is:

rdir
│   
└── code/  
    ├── processed/  
    └── raw/

**Comment by maRce10** [comment]
fixed maRce10/sketchy@075413c7b04bb16099c312ac4a31a4a5e3b64f43
