### ISSUE TITLE
"Error in tolower" when creatin compendiums. Error Prevents Printing Skeletons

### ISSUE THREAD

**Issue by andreaarriaga** [maRce10/sketchy#15]
All the types of compendiums are having errors, but it is still creating the folders.

Code:

> make_compendium(name = "project_workflowr_skeleton", path = path, format = "workflowr") # Da error pero si crea la carpeta

Creating directories ...
Error in tolower(xfun::file_ext(input)) : 
  lazy-load database '/home/andrea/R/x86_64-pc-linux-gnu-library/4.3/xfun/R/xfun.rdb' is corrupt
In addition: Warning messages:
1: In tolower(xfun::file_ext(input)) :
  restarting interrupted promise evaluation
2: In tolower(xfun::file_ext(input)) : internal error -3 in R_decompress1

> print_skeleton(path = paste0(path, "project_workflowr_skeleton")) # Da error

Error in lapply(list(...), as.character) : 
  lazy-load database '/home/andrea/R/x86_64-pc-linux-gnu-library/4.3/stringi/R/stringi.rdb' is corrupt
In addition: Warning messages:
1: In lapply(list(...), as.character) :
  restarting interrupted promise evaluation
2: In lapply(list(...), as.character) : internal error -3 in R_decompress1

**Comment by maRce10** [comment]
el path es adonde lo queres guardar, creo q es el error, y se debe usar file.path en vez de paste0
