### ISSUE TITLE
CITATION file outdated

### ISSUE THREAD

**Issue by fkohrt** [maRce10/sketchy#16]
The `textVersion` in the file `inst/CITATION` is outdated:

https://github.com/maRce10/sketchy/blob/819710b3c301bae86bf47b2969427d3ee4bfba33/inst/CITATION#L3-L8

Users who have v1.0.4 installed will still get a citation for v1.0.3:

```
> packageVersion("sketchy")
[1] ‘1.0.4’
> citation("sketchy")
Please cite 'sketchy' as follows:

  Araya-Salas, M., Arriaga, A. (2023), sketchy:
  research compendiums for data analysis in R. R
  package version 1.0.3.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {sketchy: research compendiums for data analysis in R},
    author = {M. Araya-Salas and A.Y. Arriaga},
    year = {2023},
  }
```

Why not delete the file, rather than updating it with every CRAN release?

**Comment by maRce10** [comment]
deleted. Thanks!
