### ISSUE TITLE
provide a few styles for folder structure

### ISSUE THREAD

**Issue by maRce10** [maRce10/sketchy#3]

**Comment by andreaarriaga** [comment]
[Ejemplos de estructuras de repositorios.pdf](https://github.com/maRce10/sketchy/files/5600726/Ejemplos.de.estructuras.de.repositorios.pdf)

Me encontré en una búsqueda rápida estas estructuras para organizar los folders. Funcionan?

**Comment by maRce10** [comment]
gracias! podrias ponerlas como un vector de caracteres? algo asi:

`basic <- c("data",
           "data/raw",
           "data/process",
           "output",
           "scripts",
           "manuscript")`

y tambien comentarios explicando cada carpeta, algo asi:

`basic_comments <-
  c(
    "",
    "original data",
    "modified/rearranged data",
    "all non-data products of data analysis",
    "code",
    "manuscript/poster figures"
  )`

**Comment by andreaarriaga** [comment]
[templates.txt](https://github.com/maRce10/sketchy/files/5610056/templates.txt)

Son muy breves los comentarios?  puse lo que lxs autorxs mencionaban, y un par de explicaciones que no estaban en algunos casos

**Comment by andreaarriaga** [comment]
Aquí está con nuevas opciones de formatos, mayúsculas en los comentarios y "/" al final del nombre de las carpetas
[templates.txt](https://github.com/maRce10/sketchy/files/5611564/templates.txt)

**Comment by maRce10** [comment]
Gracias!
